{
 "title": "PostgreSQL Top Queries",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "top_calls",
    "label": "internal variable for top_calls",
    "query": "query_result(topk(10, increase(pg_stat_statements_calls{instance=\"$instance\",datname=\"$db\"}[${__range_s}s])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Time consuming queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(pg_stat_statements_total_time_seconds{instance=\"$instance\", datname=\"$db\"}[5m])"
    }
   ]
  },
  {
   "title": "Most frequent queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$instance\",datname=\"$db\"}[5m])"
    }
   ]
  },
  {
   "title": "Total number of rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_rows{instance=\"$instance\", datname=\"$db\"}[5m])"
    }
   ]
  },
  {
   "title": "Slowest individual queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_statements_max_time_seconds{instance=\"$instance\",datname=\"$db\"}"
    }
   ]
  }
 ]
}