{
 "title": "PostgreSQL Single query Statistics",
 "time": { "from": "2020-02-06T09:53:35.460Z", "to": "2020-02-06T10:12:04.222Z" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "queryid",
    "label": "Query ID",
    "query": "label_values(pg_stat_statements_calls, queryid)"
   }
  ]
 },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  calls AS \"time\",\n  query AS metric,\n  query\nFROM pg_stat_statements\nWHERE\n  queryid = $queryid\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number of Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$instance\", queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Number of Rows",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_statements_rows{instance=\"$instance\", queryid=\"$queryid\"}/pg_stat_statements_calls{instance=\"$instance\", queryid=\"$queryid\"}",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Query Total time (increase over 5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_statements_total_time_seconds{instance=\"$instance\", queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Query mean time (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_statements_mean_time_seconds{instance=\"$instance\", queryid=\"$queryid\"}",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Query max time (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_statements_max_time_seconds{instance=\"$instance\", queryid=\"$queryid\"}",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  { "title": "Shared blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Blocks read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_read{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Blocks written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_statements_shared_blks_written{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Blocks dirtied",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_statements_shared_blks_dirtied{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  { "title": "Temp Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Blocks read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_blks_read{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Blocks written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_blks_written{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Blocks dirtied",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_blks_dirtied{instance=\"$instance\",queryid=\"$queryid\"}[5m])",
     "legendFormat": "{{instance}}-{{queryid}}"
    }
   ]
  }
 ]
}