{
 "title": "PostgreSQL Table Statistics",
 "time": { "from": "2020-02-06T09:57:03.159Z", "to": "2020-02-06T10:09:25.482Z" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "relname",
    "label": "Relation",
    "query": "label_values(pg_stat_user_tables_idx_scan{instance=\"$instance\"}, relname)"
   }
  ]
 },
 "panels": [
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vacuum threshold",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{instance=\"$instance\", relname=\"$relname\"}",
     "legendFormat": "{{relname}} live tuples"
    },
    {
     "expr": "pg_stat_user_tables_n_dead_tup{instance=\"$instance\", relname=\"$relname\"}",
     "legendFormat": "{{relname}} dead tuples"
    },
    {
     "expr": "pg_settings_autovacuum_vacuum_threshold + pg_settings_autovacuum_vacuum_scale_factor{instance=~\"$instance\"} * ignoring(relname, schemaname) pg_stat_user_tables_n_live_tup{instance=~\"$instance\", relname=~\"$relname\"}",
     "legendFormat": "{{relname}} vacuum threshold"
    }
   ]
  },
  {
   "title": "Last Vacuum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_vacuum{instance=\"$instance\", relname=\"$relname\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Analyze",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_analyze{instance=\"$instance\", relname=\"$relname\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Autovacuum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autovacuum{instance=\"$instance\", relname=\"$relname\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Autoanalyze",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autoanalyze{instance=\"$instance\", relname=\"$relname\"} * 1000"
    }
   ]
  },
  { "title": "Scan statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Table index scan",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{instance=\"$instance\",relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Table seq scan",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Table changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} inserts"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} deletes"
    },
    {
     "expr": "pg_stat_user_tables_n_tup_upd{instance=\"$instance\", relname=\"$relname\"}",
     "legendFormat": "{{relname}} updates"
    },
    {
     "expr": "pg_stat_user_tables_n_tup_hot_upd{instance=\"$instance\", relname=\"$relname\"}",
     "legendFormat": "{{relname}} hot updates"
    }
   ]
  },
  { "title": "Tables IO statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_hit{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} hits"
    },
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_read{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} read"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_hit{instance=\"$instance\",relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} hits"
    },
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_read{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} read"
    }
   ]
  },
  {
   "title": "Toast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_hit{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} hits"
    },
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_read{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} read"
    }
   ]
  },
  {
   "title": "Toast Indexes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_tidx_blks_hit{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} hits"
    },
    {
     "expr": "rate(pg_statio_user_tables_tidx_blks_read{instance=\"$instance\", relname=\"$relname\"}[5m])",
     "legendFormat": "{{relname}} read"
    }
   ]
  }
 ]
}